# Generated by Django 4.0.4 on 2022-06-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='num_c',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='num_e',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='infrastructure',
            old_name='num_i',
            new_name='id',
        ),
    ]
