# Generated by Django 4.0.4 on 2022-05-24 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0004_auto_20220506_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='email',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 12, 0, 55, 570883)),
        ),
    ]
